Add CheckBranch

diff --git a/.github/workflows/DeployToDev.yml b/.github/workflows/DeployToDev.yml
--- a/.github/workflows/DeployToDev.yml
+++ b/.github/workflows/DeployToDev.yml
@@ -52,7 +52,21 @@ on:
         required: false
 
 jobs:
+  CheckBranch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        run: |
+          if '${{ startsWith(inputs.ref_name, 'feature/') }}';
+          then
+            echo "Valid branch ${{ inputs.ref_name }}"
+          else
+            echo "Invalid branch ${{ inputs.ref_name }}"
+            exit 1
+          fi
+
   GetAwsValue:
+    needs: [CheckBranch]
     uses: ./.github/workflows/GetAwsValue.yml
     with:
       environment: ${{ inputs.environment }}
diff --git a/.github/workflows/DeployToProd.yml b/.github/workflows/DeployToProd.yml
--- a/.github/workflows/DeployToProd.yml
+++ b/.github/workflows/DeployToProd.yml
@@ -53,8 +53,22 @@ on:
         required: false
 
 jobs:
+  CheckBranch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        run: |
+          if '${{ inputs.ref_name == 'main' }}';
+          then
+            echo "Valid branch ${{ inputs.ref_name }}"
+          else
+            echo "Invalid branch ${{ inputs.ref_name }}"
+            exit 1
+          fi
+
   # Main 브랜치에서 가장 최근의 TAG를 가져온다
   GetLatestTag:
+    needs: [CheckBranch]
     if: ${{ inputs.ref_name == 'main' }}
     uses: ./.github/workflows/GetLatestTag.yml
     with:
@@ -66,7 +80,7 @@ jobs:
   GetCommitFromTag:
     if: ${{ inputs.ref_name == 'main' }}
     uses: ./.github/workflows/GetCommitFromTag.yml
-    needs: GetLatestTag
+    needs: [GetLatestTag]
     with:
       tag: ${{ needs.GetLatestTag.outputs.tag }}
       repository: ${{ inputs.repository }}
@@ -74,6 +88,7 @@ jobs:
 
   # 배포 시 필요한 값 가져오기
   GetAwsValue:
+    needs: [CheckBranch]
     uses: ./.github/workflows/GetAwsValue.yml
     with:
       environment: ${{ inputs.environment }}
diff --git a/.github/workflows/DeployToStg.yml b/.github/workflows/DeployToStg.yml
--- a/.github/workflows/DeployToStg.yml
+++ b/.github/workflows/DeployToStg.yml
@@ -54,9 +54,23 @@ on:
         required: false
 
 jobs:
+  CheckBranch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        run: |
+          if '${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}';
+          then
+            echo "Valid branch ${{ inputs.ref_name }}"
+          else
+            echo "Invalid branch ${{ inputs.ref_name }}"
+            exit 1
+          fi
+
   # release/hotfix 브랜치에서 발행된 최신의 rc 태깅을 찾는다.
   GetLatestTag:
     if: ${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}
+    needs: [CheckBranch]
     uses: ./.github/workflows/GetLatestTag.yml
     with:
       environment: ${{ inputs.environment }}
@@ -67,7 +81,7 @@ jobs:
   GetCommitFromTag:
     if: ${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}
     uses: ./.github/workflows/GetCommitFromTag.yml
-    needs: GetLatestTag
+    needs: [GetLatestTag]
     with:
       tag: ${{ needs.GetLatestTag.outputs.tag }}
       repository: ${{ inputs.repository }}
@@ -75,6 +89,7 @@ jobs:
 
   # 배포 시 필요한 값 가져오기
   GetAwsValue:
+    needs: [CheckBranch]
     uses: ./.github/workflows/GetAwsValue.yml
     with:
       environment: ${{ inputs.environment }}
diff --git a/.github/workflows/SetTagForProd.yml b/.github/workflows/SetTagForProd.yml
--- a/.github/workflows/SetTagForProd.yml
+++ b/.github/workflows/SetTagForProd.yml
@@ -22,10 +22,24 @@ on:
         required: true
 
 jobs:
+  CheckBranch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        run: |
+          if '${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}';
+          then
+            echo "Valid branch ${{ inputs.ref_name }}"
+          else
+            echo "Invalid branch ${{ inputs.ref_name }}"
+            exit 1
+          fi
+
   # release/hotfix 브랜치에서 배포 버전 추출
   # hotfix 브랜치면 1.0.0+hotfix.yymmdd
   # release 브랜치면 1.0.0+yymmdd
   ExtractVersion:
+    needs: [CheckBranch]
     if: ${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}
     runs-on: ubuntu-latest
     outputs:
diff --git a/.github/workflows/SetTagForStg.yml b/.github/workflows/SetTagForStg.yml
--- a/.github/workflows/SetTagForStg.yml
+++ b/.github/workflows/SetTagForStg.yml
@@ -22,9 +22,23 @@ on:
         required: true
 
 jobs:
+  CheckBranch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        run: |
+          if '${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}';
+          then
+            echo "Valid branch ${{ inputs.ref_name }}"
+          else
+            echo "Invalid branch ${{ inputs.ref_name }}"
+            exit 1
+          fi
+
   # release/hotfix 브랜치에서 가장 최신의 rc버전 태그를 가져온다
   # 브랜치 명과 동일한 rc 태그만 가져온다.
   GetLatestRcTag:
+    needs: [CheckBranch]
     if: ${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}
     uses: ./.github/workflows/GetLatestTag.yml
     with:
@@ -35,7 +49,7 @@ jobs:
   # release/hotfix 브랜치에서 새로운 RC버전 추출 (기존 rc 버전에서 1 증가 후 태깅)
   SetTagForStg:
     if: ${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}
-    needs: GetLatestRcTag
+    needs: [GetLatestRcTag]
     runs-on: ubuntu-latest
     outputs:
       tag: ${{ env.TAG }}
@@ -105,6 +119,7 @@ jobs:
           tag: ${{ env.TAG }}
 
   ExtractMilestone:
+    needs: [CheckBranch]
     if: ${{ startsWith(inputs.ref_name, 'release/') || startsWith(inputs.ref_name, 'hotfix/') }}
     runs-on: ubuntu-latest
     outputs:
